dockerui/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('registries/', include('registry.urls')),
    path('images/', include('images.urls')),
    path('containers/', include('containers.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]
handler404 = views.error_404_view

images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_user, name='logout')
]

images/models.py
from django.db import models


class Image(models.Model):
    repository = models.CharField(max_length=1000)
    image_id = models.CharField(max_length=100, null=True)
    image_short_id = models.CharField(max_length=100, null=True)
    tags = models.CharField(max_length=1000, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.repository

images/forms.py
from django import forms
from .models import Image
from registry.models import Registry
from django.forms import TextInput, ModelChoiceField, Select, IntegerField, NumberInput

class ImageForm(forms.ModelForm):
    registry = ModelChoiceField(queryset=Registry.objects.all(), widget=Select(attrs={'class': 'form-control'}))
    tag = IntegerField(label='Tag', required=True, widget=NumberInput(attrs={'class': 'form-control'})) 

    class Meta:
        model = Image
        fields = ['repository']
        widgets = {
            'repository': TextInput(attrs={
               'class': 'form-control'
            })
        }

images/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Image
from .forms import ImageForm
from registry.models import Registry
from django import forms
import docker_client
import logging
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)


@login_required
def index(request):
    models = Image.objects.order_by('-pub_date')
    # docker_images = docker_client.image_list()
    return render(request, 'images/index.html', {'models': models})

@login_required
def detail(request, id):
    model = get_object_or_404(Image, pk=id)
    inspect = docker_client.image_inspect(model.tags[2:-2])
    return render(request, 'images/detail.html', {'model': model, 'inspect': inspect})

@login_required
def create(request):
    if request.method == 'POST':
        form = ImageForm(request.POST)
        if form.is_valid():
            logger.info(form.cleaned_data['repository'] + str(form.cleaned_data['tag']))
            docker_image = docker_client.image_pull(form.cleaned_data['repository'], str(form.cleaned_data['tag']))
            model = Image()
            model.repository = form.cleaned_data['repository']
            model.image_id = docker_image.id
            model.image_short_id = docker_image.id
            model.tags = docker_image.tags
            model.save()
            return redirect('images:detail', model.pk)
    else:
        form = ImageForm()
    return render(request, 'images/create.html', {'form': form})

@login_required
def update(request, id):
    model = get_object_or_404(Image, pk=id)
    form = ImageForm(request.POST or None, instance=model)
    if request.method == 'POST':
        if form.is_valid():
            model = form.save()
            return redirect('images:detail', model.pk)
        else:
            form = ImageForm(model)
    return render(request, 'images/edit.html', {'form': form, 'model': model})

@login_required
def delete(request, id):
    model = get_object_or_404(Image, pk=id)
    docker_client.image_remove(model.repository)
    model.delete()
    return redirect('images:index')

images/templates/images/_form.html
<h1>{{ model.name }}</h1>

{% if form.password.errors %}
    <ol>
        {% for error in form.password.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
{% endif %}
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-success btn-sm" type="submit" value="Pull">
<a class="btn btn-primary btn-sm" href="{% url 'images:index' %}">Cancel</a>

images/templates/images/create.html
{% extends "base.html" %}
{% block title %}Images{% endblock %}

{% block content %}
    <h1>Pull image</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'images:create' %}" method="post">
                {% include 'images/_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

images/templates/images/detail.html
{% extends "base.html" %}
{% block title %}{{ model.name }} Images{% endblock %}

{% block content %}
    <h1>Image detail</h1>
    <div class="card">
        <div class="card-body">
            <div>ID: {{ model.image_id }}</div>
            <div>Name: {{ model.repository }}</div>
            <div>Name: {{ model.repository }}</div>
            <div>Tags: {{ model.tags }}</div>
            <div>Size: {{ inspect.Size | filesizeformat }}</div>
            <div>OS: {{ inspect.Os }} {{ inspect.Architecture }}</div>
            <hr/>
            <div>
                <a class="btn btn-primary btn-sm" href="{% url 'images:update' model.id %}">Update</a>
                <a class="btn btn-danger btn-sm" href="{% url 'images:delete' model.id %}">Delete</a>
                <a class="btn btn-warning btn-sm" href="{% url 'images:index' %}">List</a>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
        Dockerfile details
        </div>
        <div class="card-body">
            <table>
                <tr><th>CMD</th><td>{{ inspect.Config.Cmd }}</td></tr>
                <tr><th>WORKDIR</th><td>{{ inspect.Config.WorkingDir }}</td></tr>
                <tr><th>ENTRYPOINT</th><td>{{ inspect.Config.Entrypoint }}</td></tr>
                <tr><th>ENV</th><td>{% with items=inspect.Config.Env %} {% include '_ol.html' %}{% endwith %}</td></tr>
                <tr><th>VOLUMES</th><td>{{ inspect.Config.Volumes }}</td></tr>
                <tr><th>REPO DIGESTS</th><td>{% with items=inspect.RepoDigests %} {% include '_ol.html' %}{% endwith %}</td></tr>
                <tr><th>CREATED</th><td>{{ inspect.Created }}</td></tr>
            </table>
        </div>
    </div>
    <br/><br/><br/><br/>
{% endblock %}

images/templates/images/edit.html
{% extends "base.html" %}
{% block title %}Images{% endblock %}

{% block content %}
    <h1>Edit image</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'images:update' model.id %}" method="post" class="form">
                {% include 'images/_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

images/templates/images/index.html
{% extends "base.html" %}
{% block title %}Images{% endblock %}

{% block content %}
    <h1>Images</h1>
    <div class="card">
        <div class="card-header">
            <a href="{% url 'images:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Pull image</a>
        </div>
        <div class="card-body">
            {% if models %}
                <table id="table" class="table table-striped table-bordered">
                    <thead>
                    <th>Id</th>
                    <th>Repository</th>
                    <th>Tags</th>
                    <th>Size</th>
                    <th>Created</th>
                    </thead>
                    <tbody>
                    {% for model in models %}
                        <tr>
                            <td><a href="{% url 'images:detail' model.id %}">{{ model.image_short_id }}</a></td>
                            <td>{{ model.repository }}</td>
                            <td>{{ model.tags }}</td>
                            <td></td>
                            <td>{{ model.pub_date }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            {% else %}
                <p>No images are available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
{% endblock %}