containers/urls.py
from django.urls import path

from . import views

app_name = 'containers'
urlpatterns = [
    path('', views.index, name='index'),
    path('<id>/details/', views.detail, name='detail'),
    path('create/new/', views.create, name='create'),
    path('<id>/start/', views.start, name='start'),
    path('<id>/stop/', views.stop, name='stop'),
    path('<id>/kill/', views.kill, name='kill'),
    path('<id>/restart/', views.restart, name='restart'),
    path('<id>/pause/', views.pause, name='pause'),
    path('<id>/resume/', views.resume, name='resume'),
    path('<id>/delete/', views.delete, name='delete'),
    path('<id>/logs/', views.logfollow, name='logs'),
]

dockerui/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('registries/', include('registry.urls')),
    path('images/', include('images.urls')),
    path('containers/', include('containers.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]
handler404 = views.error_404_view

images/urls.py
from django.urls import path

from . import views

app_name = 'images'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_user, name='logout')
]

registry/urls.py
from django.urls import path

from . import views

app_name = 'registry'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

dockerui/views.py
from http.client import HTTPResponse
from django.http import HttpResponse

def error_404_view(request, exception):
    return HTTPResponse('Error handler content', status=404)

dockerui/templates/_ol.html
<ol>
    {% for item in items %}
        <li>{{ item }}</li>
    {% endfor %}
</ol>

dockerui/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- CSS only -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% block css %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}"/>

    <title>{% block title %}{% endblock %} - Simple docker ui</title>
    {% block html_head %}{% endblock %}
</head>
<body>
{% if user.is_authenticated %}
    {% include 'navbar.html' %}
{% else %}
    {% include 'login_navbar.html' %}
{% endif %}
<div id="content" class="container-fluid">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/07af4d1cb1.js"></script>
{% block js %}{% endblock %}
</body>

dockerui/templates/login_navbar.html
{% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary d-flex justify-content-center" id="menubar">
        <a class="navbar-brand mb-0 h1" href="{% url 'login:logout' %}">
            <button type="button" class="btn btn-light btn-sm">Log Out</button>
        </a>
    </nav>
{% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary d-flex justify-content-center" id="menubar">
        <span class="navbar-text">
            Docker UI
         </span>
    </nav>
{% endif %}

dockerui/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary d-flex justify-content-center" id="menubar">
    <div class="container-fluid d-flex justify-content-start">
        <a class="navbar-brand mb-0 h1" href="{% url 'containers:index' %}">Containers</a>
        <a class="navbar-brand mb-0 h1" href="{% url 'images:index' %}">Images</a>
        <a class="navbar-brand mb-0 h1" href="{% url 'registry:index' %}">Registry</a>
    </div>
    {% include 'login_navbar.html' %}
</nav>