dockerui/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('registries/', include('registry.urls')),
    path('images/', include('images.urls')),
    path('containers/', include('containers.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]
handler404 = views.error_404_view

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_user, name='logout')
]

registry/urls.py
from django.urls import path

from . import views

app_name = 'registry'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

registry/models.py
from django.db import models
import os


class Registry(models.Model):
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    instance_url = models.CharField(max_length=200)
    project_path = models.CharField(max_length=200)
    authentication = models.BooleanField(default=False)

    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return os.path.join(self.instance_url, self.project_path)

registry/forms.py
from django import forms
from .models import Registry
from django.forms import CharField, CheckboxInput, PasswordInput, TextInput


class RegistryForm(forms.ModelForm):
    password = CharField(label='Password', widget=PasswordInput(attrs={'class': 'form-control'}), required=True, min_length=4, max_length=100)

    class Meta:
        model = Registry
        fields = ['name', 'instance_url', 'project_path', 'authentication', 'username']
        widgets = {
            'name': TextInput(attrs={
               'class': 'form-control'
            }),
            'instance_url': TextInput(attrs={
               'class': 'form-control' 
            }),
            'project_path': TextInput(attrs={
               'class': 'form-control'
            }),
            'authentication': CheckboxInput(attrs={
               'class': 'form-check-input' 
            }),
            'username': TextInput(attrs={
               'class': 'form-control' 
            }),
        }

registry/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Registry
from .forms import RegistryForm
from django import forms
import docker_client
from django.contrib import messages
import logging
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)
@login_required
def index(request):
    models = Registry.objects.order_by('-pub_date')
    return render(request, 'registry/index.html', {'models': models})

@login_required
def detail(request, id):
    model = get_object_or_404(Registry, pk=id)
    return render(request, 'registry/detail.html', {'model': model})

@login_required
def create(request):
    if request.method == 'POST':
        form = RegistryForm(request.POST)
        if form.is_valid():
            try:
                if form.cleaned_data['authentication']:
                    res = docker_client.login(form.cleaned_data['instance_url'],
                                              form.cleaned_data['username'],
                                              form.cleaned_data['password'])
            except Exception as e:
                raise forms.ValidationError(e)
            model = form.save()
            return redirect('registry:detail', model.pk)
    else:
        form = RegistryForm()
    return render(request, 'registry/create.html', {'form': form})

@login_required
def update(request, id):
    model = get_object_or_404(Registry, pk=id)
    form = RegistryForm(request.POST or None, instance=model)
    if request.method == 'POST':
        if form.is_valid():
            try:
                res = docker_client.login(form.cleaned_data['instance_url'],
                                          form.cleaned_data['username'],
                                          form.cleaned_data['password'])
            except Exception as e:
                raise forms.ValidationError(e)

            model = form.save()
            return redirect('registry:detail', model.pk)
        else:
            form = RegistryForm(model)
    return render(request, 'registry/edit.html', {'form': form, 'model': model})

@login_required
def delete(request, id):
    model = get_object_or_404(Registry, pk=id)
    model.delete()
    return redirect('registry:index')

registry/templates/registry/_form.html
{% if form.password.errors %}
    <ol>
        {% for error in form.password.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
    </ol>
{% endif %}
{% csrf_token %}
{{ form.as_p }}
    <input class="btn btn-success btn-sm" type="submit" value="Save">
    <a class="btn btn-primary btn-sm" href="{% url 'registry:index' %}">Cancel</a>

registry/templates/registry/create.html
{% extends "base.html" %}
{% block title %}Registries{% endblock %}

{% block content %}
    <h1>Add registry</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'registry:create' %}" method="post">
                {% include 'registry/_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

registry/templates/registry/detail.html
{% extends "base.html" %}
{% block title %}{{ model.name }} Registry{% endblock %}

{% block content %}
    <h1>Registry detail</h1>
    <div class="card">
        <div class="card-body">
            <div>Name: {{ model.name }}</div>
            <div>Registry Url: {{ model.instance_url }}</div>
            <div>Project path: {{ model.project_path }}</div>
            <div>Username: {{ model.username }}</div>
            <div>Authenticate: {{ model.authentication }}</div>
            <div>Created at: {{ model.pub_date }}</div>
            <hr/>
            <div>
                <a class="btn btn-primary btn-sm" href="{% url 'registry:update' model.id %}">Update</a>
                <a class="btn btn-danger btn-sm" href="{% url 'registry:delete' model.id %}">Delete</a>
                <a class="btn btn-warning btn-sm" href="{% url 'registry:index' %}">List</a>
            </div>
        </div>
    </div>
{% endblock %}

registry/templates/registry/edit.html
{% extends "base.html" %}
{% block title %}Registries{% endblock %}

{% block content %}
    <h1>Add registry</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'registry:update' model.id %}" method="post" class="form">
                {% include 'registry/_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

registry/templates/registry/index.html
{% extends "base.html" %}
{% block title %}Registries{% endblock %}

{% block content %}
    <h1>Registries</h1>
    <div class="card">
        <div class="card-header">
            <a href="{% url 'registry:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Add registry</a>
        </div>
        <div class="card-body">
            {% if models %}
                <table id="table" class="table table-striped table-bordered">
                    <thead>
                    <th>Name</th>
                    <th>Registry Url</th>
                    <th>Project path</th>
                    <th>Authenticate</th>
                    <th>Username</th>
                    <th>Created at</th>
                    </thead>
                    <tbody>
                    {% for model in models %}
                        <tr>
                            <td><a href="{% url 'registry:detail' model.id %}">{{ model.name }}</a></td>
                            <td>{{ model.instance_url }}</td>
                            <td>{{ model.project_path }}</td>
                            <td>{{ model.authentication }}</td>
                            <td>{{ model.username }}</td>
                            <td>{{ model.pub_date }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            {% else %}
                <p>No registries are available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
{% endblock %}