containers/urls.py
from django.urls import path

from . import views

app_name = 'containers'
urlpatterns = [
    path('', views.index, name='index'),
    path('<id>/details/', views.detail, name='detail'),
    path('create/new/', views.create, name='create'),
    path('<id>/start/', views.start, name='start'),
    path('<id>/stop/', views.stop, name='stop'),
    path('<id>/kill/', views.kill, name='kill'),
    path('<id>/restart/', views.restart, name='restart'),
    path('<id>/pause/', views.pause, name='pause'),
    path('<id>/resume/', views.resume, name='resume'),
    path('<id>/delete/', views.delete, name='delete'),
    path('<id>/logs/', views.logfollow, name='logs'),
]

dockerui/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('registries/', include('registry.urls')),
    path('images/', include('images.urls')),
    path('containers/', include('containers.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]
handler404 = views.error_404_view

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_user, name='logout')
]

containers/models.py
from django.db import models
from images.models import Image


class Container(models.Model):
    container_id = models.CharField(max_length=1000)
    name = models.CharField(max_length=200)
    image = models.ForeignKey(Image, on_delete=models.NOT_PROVIDED)
    envs = models.TextField(null=True)
    ports = models.TextField(null=True)

containers/forms.py
from django import forms
from images.models import Image
from .models import Container
from django.forms import TextInput, ModelChoiceField, Select, CharField 

class ContainerForm(forms.Form):
    name = CharField(max_length=100, strip=True, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    image = ModelChoiceField(queryset=Image.objects.all(), required=True,widget=Select(attrs={'class': 'form-control'}))
    ports = CharField(max_length=3000, required=False, strip=True,widget=TextInput(attrs={'class': 'form-control'}))
    envs = CharField(required=False, strip=True,widget=TextInput(attrs={'class': 'form-control'}))

containers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Container
from .forms import ContainerForm
from registry.models import Registry
from django import forms
from django.contrib.auth.decorators import login_required
import docker_client
import logging
import json

logger = logging.getLogger(__name__)


@login_required
def index(request):
    models = docker_client.container_list()
    return render(request, 'containers/index.html', {'models': models})

@login_required
def detail(request, id):
    model = docker_client.container_get(id)
    json_attr = json.dumps(model.attrs)
    return render(request, 'containers/detail.html', {'model': model, 'inspect': model.attrs, 'json_attr': json_attr})

@login_required
def create(request):
    if request.method == 'POST':
        form = ContainerForm(request.POST)
        if form.is_valid():
            # envs = json.loads(form.cleaned_data['envs'])
            ports = json.loads(form.cleaned_data['ports'])

            docker_container = docker_client.container_create(form.cleaned_data['name'],
                                                              form.cleaned_data['image'].tags[2:-2],
                                                            #   envs,
                                                              ports)

            return redirect('containers:detail', docker_container.id)
    else:
        form = ContainerForm()
    return render(request, 'containers/create.html', {'form': form})

@login_required
def delete(request, id):
    docker_client.container_remove(id)
    return redirect('containers:index')

@login_required
def start(request, id):
    docker_client.container_start(id)
    return redirect('containers:detail', id)

@login_required
def stop(request, id):
    docker_client.container_stop(id)
    return redirect('containers:detail', id)

@login_required
def kill(request, id):
    docker_client.container_kill(id)
    return redirect('containers:detail', id)

@login_required
def restart(request, id):
    docker_client.container_restart(id)
    return redirect('containers:detail', id)

@login_required
def pause(request, id):
    docker_client.container_pause(id)
    return redirect('containers:detail', id)

@login_required
def resume(request, id):
    docker_client.container_resume(id)
    return redirect('containers:detail', id)

@login_required
def logfollow(request, id):
    lines = request.GET.get("lines", "100")

    try:
        lines = int(lines)
    except Exception as e:
        lines = "all"
    log = docker_client.container_logs(id, lines)
    return render(request, 'containers/logs.html', {'id': id, 'log': log.decode("utf-8"), 'lines': lines})

containers/templates/containers/_form.html
{% csrf_token %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
    {{ form.name.errors }}
    <label for="{{ form.name.id_for_label }}">Name:</label>
    {{ form.name }}{{ form.name.help_text }}
</div>
<div class="fieldWrapper">
    {{ form.image.errors }}
    <label for="{{ form.image.id_for_label }}">Image:</label>
    {{ form.image }}{{ form.image.help_text }}
</div>
<div class="fieldWrapper">
    {{ form.ports.errors }}
    <label for="{{ form.ports.id_for_label }}">Ports:</label>
    {{ form.ports }}{{ form.ports.help_text }}
</div>
<div class="fieldWrapper">
    {{ form.envs.errors }}
    <label for="{{ form.envs.id_for_label }}">Env</label>
    {{ form.envs }}{{ form.envs.help_text }}
</div>
<br/>
<input class="btn btn-success btn-sm" type="submit" value="Create">
<a class="btn btn-primary btn-sm" href="{% url 'containers:index' %}">Cancel</a>

containers/templates/containers/create.html
{% extends "base.html" %}
{% block title %}Create container{% endblock %}

{% block content %}
    <h1>Create container</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'containers:create' %}" method="post">
                {% include 'containers/_form.html' %}
            </form>
        </div>
    </div>
{% endblock %}

containers/templates/containers/detail.html
{% extends "base.html" %}
{% block title %}{{ model.name }} container{% endblock %}

{% block content %}
    <h1>Container detail</h1>
    <div class="card">
        <div class="card-body">
            <div>ID: {{ model.id }}</div>
            <div>Name: {{ model.name }}</div>
            <div>IP address: {{ inspect.NetworkSettings.IPAddress }}</div>
            <div>Status: {{ inspect.State.Status }}</div>
            <div>Restart count: {{ inspect.RestartCount }}</div>
            <div>Created: {{ inspect.Created }}</div>
            <div>Start time: {{ inspect.State.StartedAt }}</div>
            <hr/>
            <div>
                <div class="btn-group">
                    <a class="btn btn-sm btn-success" href="{% url 'containers:start' model.id %}">
                        <i class="fa fa-play"></i> Start
                    </a>
                    <a class="btn btn-sm btn-danger" href="{% url 'containers:stop' model.id %}">
                        <i class="fa fa-stop"></i> Stop
                    </a>
                    <a class="btn btn-sm btn-danger" href="{% url 'containers:kill' model.id %}">
                        <i class="fa fa-bomb"></i> Kill
                    </a>
                    <a class="btn btn-sm btn-primary" href="{% url 'containers:restart' model.id %}">
                        <i class="fa fa-sync"></i> Restart
                    </a>
                    <a class="btn btn-sm btn-primary" href="{% url 'containers:pause' model.id %}">
                        <i class="fa fa-pause "></i> Pause
                    </a>
                    <a class="btn btn-sm btn-primary" href="{% url 'containers:resume' model.id %}">
                        <i class="fa fa-play "></i> Resume
                    </a>
                    <a class="btn btn-sm btn-danger" href="{% url 'containers:delete' model.id %}">
                        <i class="fa fa-trash "></i> Remove
                    </a>
                </div>
                <div class="btn-group pull-right">
                    <a class="btn btn-sm btn-warning" href="{% url 'containers:logs' model.id %}">
                        <i class="fa fa-file-archive-o"></i> View logs
                    </a>
                    <a class="btn btn-sm btn-primary" href="{% url 'containers:index' %}">
                        <i class="fa fa-list "></i> Back to the list
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Container details
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>IMAGE</th>
                    <td>{{ model.image }}</td>
                </tr>
                <tr>
                    <th>PORT CONFIGURATION</th>
                    <td>{{ inspect.NetworkSettings.Ports }}</td>
                </tr>
                <tr>
                    <th>CMD</th>
                    <td>{{ inspect.Config.Cmd }}</td>
                </tr>
                <tr>
                    <th>ENTRYPOINT</th>
                    <td>{{ inspect.Config.Entrypoint }}</td>
                </tr>
                <tr>
                    <th>ENV</th>
                    <td>{% with items=inspect.Config.Env %} {% include '_ol.html' %}{% endwith %}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Volumes
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>Host/volume</th>
                    <th>Path in container</th>
                </tr>
                {% for mount in inspect.Mounts %}
                    <tr>
                        <th>{{ mount.Source }}</th>
                        <td>{{ mount.Destination }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Connected networks
        </div>
        <div class="card-body">
            <table class="table">
                <tr>
                    <th>Network</th>
                    <th>IP Address</th>
                    <th>Gateway</th>
                    <th>MAC Address</th>
                </tr>
                {% for network in inspect.NetworkSettings.Networks %}
                    <tr>
                        <th></th>
                        <td>{{ network.IPAddress }}</td>
                        <th>{{ network.Gateway }}</th>
                        <th>{{ network.MacAddress }}</th>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            Inspection
        </div>
        <div class="card-body">
            <pre>{{ json_attr | safe }}</pre>
        </div>
    </div>
    <br/><br/><br/><br/>
{% endblock %}

{% block js %}
    <script>
        let attrs = {{ json_attr | safe }};
        console.log(attrs);
    </script>
{% endblock %}

containers/templates/containers/index.html
{% extends "base.html" %}
{% block title %}Containers{% endblock %}

{% block content %}
    <h1>Containers</h1>
    <div class="card">
        <div class="card-header">
            <a href="{% url 'containers:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Add container</a>
        </div>
        <div class="card-body">
            {% if models %}
                <table id="table" class="table table-striped table-bordered">
                    <thead>
                    <th>Name</th>
                    <th>State</th>
                    <th>Image</th>
                    <th>Labels</th>
                    <th>Created</th>
                    <th>Published Ports</th>
                    </thead>
                    <tbody>
                    {% for model in models %}
                        <tr>
                            <td><a href="{% url 'containers:detail' model.id %}">{{ model.name }}</a></td>
                            <td>{{ model.status }}</td>
                            <td>{{ model.image }}</td>
                            <td>{{ model.labels }}</td>
                            <td>{{ model.attrs.Created }}</td>
                            <td>{{ model.attrs.NetworkSettings.Ports }}</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            {% else %}
                <p>No containers are available.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}


{% block css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.css"/>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.24/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
{% endblock %}

containers/templates/containers/logs.html
{% extends "base.html" %}
{% block title %}Container {% endblock %}

{% block content %}
    <h1>Logs of container</h1>
    <div class="card">
        <div class="card-header">
            <form method="get" class="form">
                <label>Lines:</label> <input name="lines" value="{{ lines }}" placeholder="all | 50"/>
                <input class="btn btn-sm btn-success" type="submit" value="View">
                <a class="btn btn-sm btn-primary pull-right" href="{% url 'containers:detail' id %}">
                    <i class="fa fa-step-backward"></i> Back to details</a>
            </form>
        </div>
        <div class="card-body">
            <pre >{{ log | safe }}</pre>
        </div>
    </div>
    <br/>
    <br/>
{% endblock %}